---
title: "News"
---
* *July 2021* - My latest work is up on [bioRxiv](https://www.biorxiv.org/content/10.1101/2021.07.13.452208v1)!Title: Prolactin and prolactin receptor expression in the HPG axis and crop during parental care in both sexes of a biparental bird (*Columba livia*)

* *June 2021* - I've begun a summer fellowship with the SEISMIC multi-institution collaborative to work on my education research on equity gaps in upper divsion science courses. Learn more about the SEISMIC summer fellows [here](https://www.seismicproject.org/working-groups/measurement/2021-measurement-fellowship/). 

* *April 2021* - My undergraduate mentee, Alison Ramirez, a [California Alliance for Minority Participation (CAMP)](https://urc.ucdavis.edu/camp) scholar, is presenting our project on how reproductive experience affects neural prolactin receptor expression! Check out her talk at the Undergraduate Research Conference by registering [here](https://docs.google.com/forms/d/e/1FAIpQLSewkh3jpA-hXP_0ChepwXLTU4AnfhOtxO2jVAsTANc-NM6TpQ/viewform?usp=send_form).

* Thank you to the Animal Behavior Society for funding my research on parental experience via a [Student Research Grant](https://www.animalbehaviorsociety.org/web/awards-student-grants.php)!

* *February 2021* - I recieved a [Grant-in-Aid-of-Research (GIAR)](https://sicb.burkclients.com/grants/giarinfo.php) from the Society of Integrative and Comparative Biology. This award is named in honor of [Dr. Abbot Gaunt](tinyurl.com/p9u98vnk), a late expert in bird vocalizations and avian anatomy. I am thankful to the funders and excited to do research following in Gaunt's scientific legacy. 

* *June 2020* - **Black Lives Matter!** In wake of the ongoing police brutality and injustices experienced by the Black community, the Ethogram released a collective statement of solidarity and committment to anti-racism in our approach to outreach and content going forward. You can read our statement [here](https://theethogram.com/2020/06/05/ethogram-statement-of-solidarity/). To amplify the voices of our Black colleagues, my advisor Dr. Calisi, editor Alexia Williams, and I put together a series of profiles highlighting Black excellence for the College of Biological Science. Read the pieces [here](https://biology.ucdavis.edu/news/dr-cameron-jones-recounts-his-work-behavioral-ecologist).

* *May 2020* - My SICB student journalism piece, highlighting research from the 2020 conference in Austin, is now published! Read it [here](http://www.sicb.org/students/2020/farrar.php).  

*  *April 2020* - I recieved the 2020 [Sharon Gray Memorial Award](https://www.ucdavis.edu/news/sharon-gray-memorial-award-established/) for undergraduate mentorship! I am thankful for the sponsorship by the Sharon Gray Foundation and donors of the College of Biological Sciences. Stay tuned for forthcoming results from my mentee's, Ana B. Molina Gil, project!