---
title: "Writing"
---

## SICB Student Journalism

As a [student science journalist](http://www.sicb.org/students/awards.php3#support) for the [SICB 2020](https://burkclients.com/sicb/meetings/2020/site/) conference, I wrote about Lucas Greville's work on hormone transfer in bats, and how he puts the "pee" in Ph.D. Read more [here](http://www.sicb.org/students/2020/farrar.php). 


## UC Davis 

### College of Biological Sciences

To amplify the voices of our Black colleagues, my advisor Dr. Calisi, along with editor Alexia Williams, spearheaded a series of profiles highlighting Black excellence for the College of Biological Science. I was able to contribute a piece featuring recent Animal Behavior graduate Dr. Cameron Jones and his work on spider "personality" and urban ecology. Read more about him [here](https://biology.ucdavis.edu/news/dr-cameron-jones-recounts-his-work-behavioral-ecologist).

### The Ethogram 

Since 2017, I've been a regular contributor to [The Ethogram](https://theethogram.com/), the official, graduate-student run blog of the Animal Behavior at UC Davis. 

See my author profile on The Ethogram [here](https://theethogram.com/author/vsfarrar/). 

Some of my favorite pieces there have covered: 

*  A mysterious run in with a chupacabra(?) while doing field work on house finches. [[Link]](https://theethogram.com/2017/12/01/field-fiasco-friday-chupacabra-attack/)  

*  How wild hyena reproductive parts are. [[Link]](https://theethogram.com/2018/05/22/creature-feature-spotted-hyena/)

*  The field fiascos involved with studying fish across the Central Valley, with former UC Davis post-doc, [Dr. Isaac Ligocki](https://isaacligocki.com/). [[Link]](https://theethogram.com/2018/01/19/field-fiasco-fish-in-the-driveway/)

*  The unsuspecting dietary choices and microbiota of the Galapagos vampire finch, where I interviewed [Dr. Dan Baldassare](https://danbaldassarre.weebly.com/) from SUNY Oswego. [[Link]](https://theethogram.com/2018/10/30/creature-feature-vampire-finch/)



